server:
  port: 8080

spring:
  application:
    name: "mini-soccer-manager"
  datasource:
    url: jdbc:mysql://localhost:3306/soccer_management_db?useSSL=false&allowPublicKeyRetrieval=true
    username: socceruser
    password: soccerpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

auth:
  token:
    jwtSecret: ${AUTH_JWT_SECRET:YXNzZWN1cmUtZGVmYXVsdC1qd3Qtc2VjcmV0LXN0cmluZw==}
    accessExpirationInMils: ${AUTH_ACCESS_EXPIRATION:86400000}

api:
  prefix: /api/v1

payment:
  vnpay:
    tmnCode: ${VNPAY_TMN_CODE:ZZYGQPJN}
    hashSecret: ${VNPAY_HASH_SECRET:ZWICAZ65X5HB62HV350SQ0H6AGN7WIF3}
    payUrl: ${VNPAY_PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    returnUrl: ${VNPAY_RETURN_URL:http://127.0.0.1:8080/api/v1/payments/vnpay/callback}
    version: ${VNPAY_VERSION:2.1.0}
    command: ${VNPAY_COMMAND:pay}
    currencyCode: ${VNPAY_CURRENCY_CODE:VND}
    locale: ${VNPAY_LOCALE:vn}
    orderType: ${VNPAY_ORDER_TYPE:other}

frontend:
  vnpay:
    callback-url: ${FRONTEND_VNPAY_CALLBACK_URL:http://127.0.0.1:3000/payment/vnpay/callback}
